# Generated by Django 4.1.7 on 2023-03-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellphoneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passWord',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
